// Export type-safe ABIs generated by wagmi CLI
// Run `pnpm generate` to regenerate these ABIs from Foundry contracts
export {
  safeModuleManagerAbi as SafeModuleManagerABI,
  managedSafeModuleAbi as ManagedSafeModuleABI,
  syncGroupRegistryAbi as SyncGroupRegistryABI
} from './generated';

// Safe contract ABI (minimal interface for external Safe interactions)
export const SafeABI = [
  {
    "inputs": [{"internalType": "address", "name": "module", "type": "address"}],
    "name": "isModuleEnabled",
    "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {"internalType": "address", "name": "prevModule", "type": "address"},
      {"internalType": "address", "name": "module", "type": "address"}
    ],
    "name": "disableModule",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"internalType": "address", "name": "module", "type": "address"}],
    "name": "enableModule",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getOwners",
    "outputs": [{"internalType": "address[]", "name": "", "type": "address[]"}],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getThreshold",
    "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
