import { Address } from 'viem';

export interface ChainDeployments {
  SafeModuleManager?: Address;
  ManagedSafeModule?: Address;
  SyncGroupRegistry?: Address;
  OwnerModuleFactory?: Address;
  ControlOwnerModule?: Address;
}

/**
 * Deployment addresses extracted from broadcast files
 * Auto-generated by scripts/update-deployments.ts
 * Last updated: 2026-01-15
 *
 * Manually updated to include Base deployment
 */
const DEPLOYMENT_ADDRESSES: Record<number, ChainDeployments> = {
  // Gnosis Chain
  100: {
    SafeModuleManager: '0x3CB556694b77974D6BA0184c0cD58da26ebfCAB5',
    ManagedSafeModule: '0x62D0a51d937887Df56D6dF250Eb1eba79be1d2Ce',
    SyncGroupRegistry: '0x1d9aafd517d85450bD85169eF291298a016da202',
  },
  // Base
  8453: {
    SafeModuleManager: '0x5b06966f52ccf21d77cfb9009cdb896139249079',
    ManagedSafeModule: '0xb8710ab0ad28e2114f8a4cdd6062ce200a587a30',
    SyncGroupRegistry: '0x0278b0aecb2772ade61a8a5d4ec1ee6b163c12a0',
  }
};

/**
 * Get deployment addresses for a specific chain
 */
export function getDeploymentAddresses(chainId: number): ChainDeployments {
  return DEPLOYMENT_ADDRESSES[chainId] || {};
}

/**
 * Get deployed address for a specific contract on a chain
 */
export function getDeployedAddress(
  chainId: number,
  contractName: keyof ChainDeployments
): Address | undefined {
  const addresses = getDeploymentAddresses(chainId);
  const address = addresses[contractName];

  console.log(`[Deployments] Getting ${contractName} for chain ${chainId}`);
  console.log(`[Deployments] Available contracts:`, Object.keys(addresses));
  console.log(`[Deployments] Address found:`, address);

  return address;
}

/**
 * Get SafeModuleManager address for a chain, with fallback to OwnerModuleFactory
 */
export function getSafeModuleManagerAddress(chainId: number): Address | undefined {
  const addresses = getDeploymentAddresses(chainId);
  return addresses.SafeModuleManager || addresses.OwnerModuleFactory;
}

/**
 * Get ManagedSafeModule template address for a chain, with fallback to ControlOwnerModule
 */
export function getManagedSafeModuleAddress(chainId: number): Address | undefined {
  const addresses = getDeploymentAddresses(chainId);
  return addresses.ManagedSafeModule || addresses.ControlOwnerModule;
}

/**
 * Get block explorer URL for a chain
 */
export function getBlockExplorerUrl(chainId: number): string {
  const explorers: Record<number, string> = {
    1: 'https://etherscan.io',
    100: 'https://gnosisscan.io',
    8453: 'https://basescan.org',
    11155111: 'https://sepolia.etherscan.io',
    84532: 'https://sepolia.basescan.org',
    31337: 'http://localhost:8545',
  };
  return explorers[chainId] || 'https://etherscan.io';
}

/**
 * Contract versions
 */
export const CONTRACT_VERSIONS = {
  SafeModuleManager: 'v2.0.0-uups',
  ManagedSafeModule: 'v2.0.0-uups',
  SyncGroupRegistry: 'v1.0.0-uups',
} as const;
