[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@gnosis.pm/safe-contracts/contracts/common/Enum.sol=lib/safe-contracts/contracts/common/Enum.sol",
    "@gnosis.pm/safe-contracts/contracts/=lib/safe-contracts/contracts/",
    "@gnosis.pm/safe-contracts/=lib/safe-contracts/",
    "@gnosis.pm/=lib/",
    "@zodiac/=lib/zodiac/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
